.gitignore
Gemfile
Gemfile.lock
db/seeds.rb

seeds users done

---

app/controllers/users_controller.rb

users#show

---

app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb

I've implemented the sign in pages with devise. With routes etc.

sign in implemented

---

app/controllers/users_controller.rb

users method edit

---

app/controllers/users_controller.rb

update method to users

---

app/views/users/show.html.erb

user#show view

---

app/controllers/activities_controller.rb
app/views/activities/new.html.erb

Activities controller methods (new & create) + new view

Activities controller methods

---

app/views/activities/new.html.erb

form btn edit

---

app/views/moments/partials/_card.html.erb
db/seeds.rb

Seeds well done

---

app/models/moment.rb
app/views/moments/edit.html.erb
app/views/moments/new.html.erb
db/migrate/20180821123137_remove_level_from_moments.rb
db/schema.rb
db/seeds.rb

add select to form (new & update)

form select

---

app/controllers/moments_controller.rb
app/views/moments/destroy.html.erb
app/views/moments/show.html.erb

see with a ti and its work !  @AntoineCoconut

method delete ok + redirect

---

Gemfile.lock
app/controllers/moments_controller.rb
app/views/moments/show.html.erb

no edit btn on show if user is no good !

Edit moment user

---

app/controllers/moments_controller.rb
app/views/moments/show.html.erb

Moment Show, display delete btn only if good user

delete btn on moment show only if good user

---

app/controllers/bookings_controller.rb
app/controllers/users_controller.rb
app/policies/booking_policy.rb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb
test/policies/booking_policy_test.rb

Bookings Controller/view & Pundit !

Bookings Controller

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/moments_controller.rb
app/views/moments/show.html.erb

The date is now managed by the view from the date picked in the moment creation.
/!\ old dates manually entered (before datepicker) can be mal-formatted. You should remove the two lines "@formatted_start / @formatted_end" from the moments controller (copy-paste), then edit the moment in the browser to pick dates with date picker, then repaste the two lines and it should work.

date display ok

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/views/moments/edit.html.erb
app/views/moments/new.html.erb
app/views/shared/_navbar.html.erb

mise en forme basique des formulaire plus fix probleme login/logout

forms-layout

---

app/assets/stylesheets/components/_form.scss
app/views/bookings/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

Devise forms layout

---

app/views/users/_form.html.erb

edit bio fomr layout

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

@AntoineCoconut & @ghbozz 
Problem fixed bug sur la navbar

 navbar fixed

---

app/assets/stylesheets/components/_form.scss
app/views/moments/edit.html.erb
app/views/moments/new.html.erb
app/views/users/_form.html.erb

form layout

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/moments/_index.scss
app/assets/stylesheets/moments/_show.scss
app/views/moments/show.html.erb

css moments show draft

---

app/controllers/moments_controller.rb
app/views/moments/show.html.erb

Join form in moment show + list of bookings in moment show

join form in moment show

---

app/controllers/bookings_controller.rb

user c'ant join their own moment // user can't join a moment multiple times

user join moment restriction

---

app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/users/_show.scss
app/views/users/_card.html.erb
app/views/users/show.html.erb

first styling tbc

---

app/controllers/bookings_controller.rb
app/views/moments/show.html.erb

join form not display if moment.user == current_user

fix join restriction

---

.gitignore
app/assets/stylesheets/components/_form.scss
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
app/views/shared/_navbar.html.erb

Notifications stylish

---

Gemfile
Gemfile.lock
app/controllers/moments_controller.rb
app/javascript/packs/map.js
app/models/moment.rb
app/views/layouts/application.html.erb
app/views/moments/show.html.erb
config/initializers/geocoder.rb
db/migrate/20180823103803_add_coordinates_to_moments.rb
db/schema.rb
db/seeds.rb
package.json
yarn.lock

Geocoder basic implement
U have to bundle install & yarn install !!!

geocoder tbc

---

app/controllers/moments_controller.rb
app/views/moments/index.html.erb

Search by location and activity name

search tbc

---

app/assets/stylesheets/moments/_index.scss
app/views/moments/_card.html.erb
app/views/moments/index.html.erb

@AntoineCoconut @ghbozz 
ok pour button on search +padding

search button and css

---

app/views/shared/_navbar.html.erb

good avatar picture on navbar when login

navbar avatar user good

---

app/views/moments/_card.html.erb

@AntoineCoconut @ghbozz c'est ok juste le css deconne mais j'y ai pas touché

ok mais la description se barre en couille..

---

app/views/shared/_navbar.html.erb

cleanup dropdown link

---

app/views/moments/_card.html.erb

card are now btn

---

app/views/users/show.html.erb

rating user done

---

app/assets/stylesheets/moments/_index.scss
app/assets/stylesheets/moments/_new.scss
app/views/moments/new.html.erb

image on moment new

---

app/assets/stylesheets/components/_navbar.scss
app/views/users/_card.html.erb
app/views/users/show.html.erb

io !! j'ai ajouter les une section 'my moments' sur le profil utilisateur, j'en ai aussi profité pour ajouter sur le profil un bouton details pour aller sur la show de chaque bookings...
et un tres leger border-bottom sur la navbar
ps: Antoine j'ai pas oser faire la carte qui va avec je voulais pas foutre la merde donc pour le moment y'a juste l'objet moment afficher sur le profil

add my moment on profil

---

Gemfile
Gemfile.lock
app/controllers/moments_controller.rb
app/models/moment.rb
app/views/moments/index.html.erb

je viens d'ajouter pg-search donc maintenant on peut search par location, activity et category et les 3 en meme temps j'ai aussi ajouter un petit compteur en haut de l'index qui indique le nombre de resultat d'une recherche
oubliez pas de bundle install pour la gem 'pg-search'
a demain

add pg-search

---

app/assets/stylesheets/users/_show.scss

width fixed

---

app/assets/stylesheets/moments/_show.scss
app/views/moments/show.html.erb

add countdown on moment#show page

countdown ok

---

app/views/moments/show.html.erb

if statement on countdown Today / 1 day / x days

plural on countdown

---

app/assets/stylesheets/users/_card.scss
app/assets/stylesheets/users/_show.scss
app/views/users/_card.html.erb
app/views/users/show.html.erb

fixed moments user show

---

app/assets/stylesheets/moments/_show.scss
app/views/moments/show.html.erb

countdown cool over 3 days

---

app/assets/stylesheets/moments/_show.scss

fixed modal
